### ISSUE TITLE
Assignment 1 To-Do List

### ISSUE THREAD

**Issue by FireAlfa** [FireAlfa/TurboTribble#1]
# Assignment 1 To-Do List

## FBX and GameObject
 - [x] Baker_house should be automatically loaded at the start.
 - [x] Your two models must be in FBX format with one channel diffuse texture.
 - [x] It should accept drag&drop of FBX files from anywhere in the Hard Drive.
 - [x] It should accept drag&drop of DDS/PNG files (apply the texture to the selected GameObject).
 - [x] There must be a GameObject structure, one for each loaded mesh. Each GameObject should have, at least, 3 display-only components: Transform, Mesh and Texture.

## Unity-like camera controls
 - [x] While Right clicking, “WASD” fps-like movement and free look around must be enabled.
 - [x] Mouse wheel should zoom in and out.
 - [x]  Alt+Left click should orbit the object.
 - [x] Pressing “f” should focus the camera around the geometry.
 - [x] Holding SHIFT duplicates movement speed.

## Editor Windows
 - [x] Console Window: the window should LOG the geometry loading process from ASSIMP and the external libraries initialization process.
 - [x] Configuration Window: A graph for the frames per second.
 - [x] Configuration Window: Configuration for all variables on each module (renderer, window, input, textures).
 - [x] Configuration Window: Information output of memory consumption, hardware detection and software versions (SDL, OpenGL, DevIL).
 - [x] Hierarchy: you should display a list with all GameObjects in this window. The user should be able to select a GameObject through this window.
 - [x] Inspector: you should display information about the components of the selected GameObject.
 - [x] Transform: only for display purposes. Show position, rotation and scale for the selected GameObject.
 - [x] Mesh: information about the loaded mesh. There should be an option to display its normals (per-triangle and per-face).
 - [x] Texture: display texture size and path. There should be an option to view the selected GameObject with the checkers texture.

## Menu Bar
 - [x] File Menu: Option to Quit.
 - [x] Help Menu: Visit the GitHub page and get info about the engine ("About").
 - [x] Windows Menu: It should be able to turn on/off editor windows.
 - [x] GameObject Menu: There must be a menu to load your own basic shapes ("Primitives").
