### ISSUE TITLE
Assignment 2 To-Do List

### ISSUE THREAD

**Issue by FireAlfa** [FireAlfa/TurboTribble#3]
# Assignment 2 To-Do List

## Start
- [x] The ‘Street Environment’ scene should be automatically loaded at the start. You can edit the original model if necessary.

## GameObject Inspector
- [x] Hierarchy: delete, reparent, create empty and create children.
- [x] Transform: translate, rotate and scale Game Objects.
- [ ]  Mesh: select or drop any imported mesh.
- [ ] Texture: select or drop any imported texture.
- [x] Camera is a component with settings that can be modified.

## Mouse Picking
- [x] GameObjects can be picked from the world using the mouse.
- [x] All meshes use a bounding volume (AABB) and can be discarded using Frustum Culling. This process should be visualized in the editor (debug raycast and boxes).

## File
- [x] Models, meshes and textures are saved to your own format under “Library” folder
- [ ] Scene can be serialized to a file that can be loaded.

## Time Management
- [ ] The user can Start / Pause / Stop the simulation and recover its original state.
- [x] The editor has 2 windows one with the scene(editor view) and another captured from a gameobject with a camera component (main game camera), each one has its own framebuffer and the user can visualize both at the same time.

## Resource Management
- [x] There is an “Assets” window that shows all user assets * it can be a simple tree viewer
- [ ] The user can drop/import new files. Assets window reacts properly
- [ ] Asset files can be deleted through the window and /Library entries are removed
- [ ] Upon start, all resources not managed inside Assets are generated in Library */Library folder should be regenerated from /Assets + meta content
- [ ] All resources use reference counting (e.g. a texture / mesh is only once in memory regardless of how many gameobject use it). This requires this process to be visualized in the editor.

**Comment by FireAlfa** [comment]
PDF List:
- [ ] 08 - Custom File Format
- [ ] 09 - Serialization
- [x] 10 - Frustum Culling
- [x] 11 - Mouse Picking
- [ ] 12 - Space Partitioning
- [ ] 13 - Time Management
- [ ] 14 - Event System
- [ ] 15 - Resource Management
